### ISSUE TITLE
Upwork issue

### ISSUE THREAD

**Issue by michaelschultzdev** [LuckyBoy1004/Monitoring#1]
Hey man, Michael here from upwork. Looks like there was an issue with your account or something, I couldn't find any other way of contacting you. If you do email then I'm at michael@apexrush.com. If telegram I'm https://t.me/MikeSoliDefi

**Comment by LuckyBoy1004** [comment]
Hi, Michael, Thank you for your messaging.
I saw my account has problem now, I am trying to solve that.
I will contact you vai telegram.
Thanks again.
